apiVersion: v1
kind: Secret
metadata:
    name: mongo-secret
    namespace: mongodb
data:
#USUALLY NEVER PUT SECRETS IN GIT. But this is demo.
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=